### ISSUE TITLE
NewAsyncProducer panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by youngperson** [IBM/sarama#1652]
##### mster(af1423)

| Sarama | Kafka | Go |
|--------|-------|----|
| af1423 | kafka_2.12-2.2.0 | go1.12.7 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
	config := sarama.NewConfig()
	config.Net.KeepAlive = time.Duration(3) * time.Millisecond
	config.Net.DialTimeout = time.Duration(cfg.ConnectTimeout) * time.Millisecond
	config.Producer.Return.Errors = true
	config.Producer.RequiredAcks = sarama.WaitForLocal       // Only wait for the leader to ack
	config.Producer.Flush.Frequency = 500 * time.Millisecond // Flush batches every 500ms
	config.Producer.Partitioner = sarama.NewRandomPartitioner
```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
[Sarama] 2020/03/24 17:44:35 producer/broker/3 state change to [retrying] on overmind-msg-test/2 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.
[Sarama] 2020/03/24 17:44:35 producer/leader/overmind-msg-test/5 state change to [retrying-1]
[Sarama] 2020/03/24 17:44:35 producer/leader/overmind-msg-test/5 abandoning broker 2
[Sarama] 2020/03/24 17:44:35 producer/leader/overmind-msg-test/9 state change to [retrying-1]
[Sarama] 2020/03/24 17:44:35 producer/broker/3 state change to [retrying] on overmind-msg-test/1 because kafka server: Tried to send a message to a replica that is not the leader for some partition. Your metadata is out of date.

==========

panic: sync: negative WaitGroup counter

goroutine 709 [running]:
sync.(*WaitGroup).Add(0xc000b32658, 0xffffffffffffffff)
	/usr/local/go/src/sync/waitgroup.go:74 +0x135
sync.(*WaitGroup).Done(...)
	/usr/local/go/src/sync/waitgroup.go:99
github.com/Shopify/sarama.(*asyncProducer).returnSuccesses(0xc000b32620, 0xc007e28000, 0x78a, 0x900)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:1055 +0x3c
github.com/Shopify/sarama.(*brokerProducer).handleSuccess.func1(0xc00024c0a1, 0x11, 0xc00000000a, 0xc00b53a880)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:878 +0x1d3
github.com/Shopify/sarama.(*produceSet).eachPartition(0xc0055ffea0, 0xc00ac19da8)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/produce_set.go:201 +0xb4
github.com/Shopify/sarama.(*brokerProducer).handleSuccess(0xc000b88770, 0xc0055ffea0, 0xc0037375e0)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:854 +0x9e
github.com/Shopify/sarama.(*brokerProducer).handleResponse(0xc000b88770, 0xc00ab48ae0)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:842 +0x13e
github.com/Shopify/sarama.(*brokerProducer).run(0xc000b88770)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:771 +0xaee
github.com/Shopify/sarama.withRecover(0xc00b56dd50)
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/utils.go:43 +0x43
created by github.com/Shopify/sarama.(*asyncProducer).newBrokerProducer
	/home/jenkins/jobs/HZ-overmind-yace/workspace/gopath/src/github.com/Shopify/sarama/async_producer.go:658 +0x1c2
```

</p>
</details>

**Comment by dnwe** [comment]
Not something I've seen before, but found in quite an old version. Please re-open if this is something you've seen on recent versions
