### ISSUE TITLE
Creating a client with mock broker in tests hangs indefinitely

### ISSUE THREAD

**Issue by GM-GaggunChaggar** [IBM/sarama#2476]
##### Versions

*Please specify real version numbers or git SHAs, not just "Latest" since that changes fairly regularly.*

| Sarama | Kafka | Go |
|--------|-------|----|
| v1.38.1 | v2.7 | 1.20 |

##### Configuration

What configuration values are you using for Sarama and Kafka?
``` go
package main_test

import (
	"fmt"
	"testing"

	"github.com/Shopify/sarama"
	"github.com/Shopify/sarama/mocks"
)

func TestRun(t *testing.T) {
	mockBroker := initMockBroker(t, "group")
	cnf := mocks.NewTestConfig()
	cnf.Version = sarama.V2_7_0_0
	cnf.Consumer.Return.Errors = true
	cnf.ClientID = "test"
	cnf.Consumer.Offsets.Initial = sarama.OffsetNewest

	fmt.Printf("address: %s \n", mockBroker.Addr())

	client, _ := sarama.NewClient([]string{mockBroker.Addr()}, cnf)
	fmt.Println("Got client")

	sarama.NewConsumerGroupFromClient("group", client)
	fmt.Println("Got Group")
}

func initMockBroker(t *testing.T, group string) *sarama.MockBroker {
	mockBroker := sarama.NewMockBroker(t, 0)
	mockMetadataResponse := sarama.NewMockMetadataResponse(t).
		SetBroker(mockBroker.Addr(), mockBroker.BrokerID()).
		SetLeader("events", 0, mockBroker.BrokerID())
	mockProducerResponse := sarama.NewMockProduceResponse(t).
		SetError("events", 0, sarama.ErrNoError)
	mockOffsetResponse := sarama.NewMockOffsetResponse(t).
		SetOffset("events", 0, sarama.OffsetOldest, 0).
		SetOffset("events", 0, sarama.OffsetNewest, 1)
	mockFetchResponse := sarama.NewMockFetchResponse(t, 1).
		SetMessage("events", 0, 0, sarama.StringEncoder("testing 123")).
		SetMessage("events", 0, 1, sarama.StringEncoder("testing 123")).
		SetMessage("events", 0, 2, sarama.StringEncoder("testing 123")).
		SetMessage("events", 0, 3, sarama.StringEncoder("testing 123")).
		SetMessage("events", 0, 4, sarama.StringEncoder("testing 123")).
		SetMessage("events", 0, 5, sarama.StringEncoder("testing 123"))
	mockCoordinatorResponse := sarama.NewMockFindCoordinatorResponse(t).
		SetCoordinator(sarama.CoordinatorType(0), group, mockBroker)
	mockJoinGroupResponse := sarama.NewMockJoinGroupResponse(t)
	mockSyncGroupResponse := sarama.NewMockSyncGroupResponse(t).
		SetMemberAssignment(&sarama.ConsumerGroupMemberAssignment{
			Version:  0,
			Topics:   map[string][]int32{"events": {0}},
			UserData: nil,
		})
	mockHeartbeatResponse := sarama.NewMockHeartbeatResponse(t)
	mockOffsetFetchResponse := sarama.NewMockOffsetFetchResponse(t).
		SetOffset(group, "events", 0, 0, "", sarama.KError(0))

	mockBroker.SetHandlerByMap(map[string]sarama.MockResponse{
		"MetadataRequest":        mockMetadataResponse,
		"ProduceRequest":         mockProducerResponse,
		"OffsetRequest":          mockOffsetResponse,
		"OffsetFetchRequest":     mockOffsetFetchResponse,
		"FetchRequest":           mockFetchResponse,
		"FindCoordinatorRequest": mockCoordinatorResponse,
		"JoinGroupRequest":       mockJoinGroupResponse,
		"SyncGroupRequest":       mockSyncGroupResponse,
		"HeartbeatRequest":       mockHeartbeatResponse,
	})
	return mockBroker
}

```

##### Logs

When filing an issue please provide logs from Sarama and Kafka if at all
possible. You can set `sarama.Logger` to a `log.Logger` to capture Sarama debug
output.

<details><summary>logs: CLICK ME</summary>
<p>

```
go test ./... -timeout=5s
address: 127.0.0.1:57741 
panic: test timed out after 5s
running tests:
        TestRun (5s)

goroutine 6 [running]:
testing.(*M).startAlarm.func1()
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:2241 +0x328
created by time.goFunc
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/time/sleep.go:176 +0x38

goroutine 1 [chan receive]:
testing.(*T).Run(0x1400011cd00, {0x102ca0dde?, 0x898f9bd7848b?}, 0x102dd1fb0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1630 +0x37c
testing.runTests.func1(0x1400011cd00?)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:2036 +0x48
testing.tRunner(0x1400011cd00, 0x1400012fc68)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1576 +0x10c
testing.runTests(0x1400013a8c0?, {0x102fb5770, 0x1, 0x1}, {0x1400011f980?, 0x40?, 0x102fc1bc0?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:2034 +0x40c
testing.(*M).Run(0x1400013a8c0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1906 +0x58c
main.main()
        _testmain.go:47 +0x1d0

goroutine 34 [sync.Mutex.Lock]:
sync.runtime_SemacquireMutex(0x14000106ae8?, 0x18?, 0x0?)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/sema.go:77 +0x28
sync.(*Mutex).lockSlow(0x14000121c50)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/sync/mutex.go:171 +0x178
sync.(*Mutex).Lock(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/sync/mutex.go:90
github.com/Shopify/sarama.(*Broker).sendAndReceive(0x14000121c00?, {0x102dd7c60?, 0x1400010fbf0?}, {0x102dd7ca8?, 0x14000138550?})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:1027 +0xb4
github.com/Shopify/sarama.(*Broker).GetMetadata(0x2?, 0x7?)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:371 +0x50
github.com/Shopify/sarama.(*client).tryRefreshMetadata(0x1400013a960, {0x0, 0x0, 0x0}, 0x102dd5a98?, {0x14000198000?, 0x10a520218?, 0x0?})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/client.go:1007 +0x3fc
github.com/Shopify/sarama.(*client).RefreshMetadata(0x1400013a960, {0x0?, 0x0, 0x0})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/client.go:527 +0x110
github.com/Shopify/sarama.NewClient({0x14000106f48, 0x1, 0x1}, 0x14000196000)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/client.go:198 +0x204
example_test.TestRun(0x0?)
        /Users/gaggunchaggar/Desktop/kafkatest/main_test.go:21 +0x140
testing.tRunner(0x1400011cea0, 0x102dd1fb0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1576 +0x10c
created by testing.(*T).Run
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/testing/testing.go:1629 +0x368

goroutine 37 [IO wait]:
internal/poll.runtime_pollWait(0x10a51e8f8, 0x72)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x14000170280?, 0x102a47618?, 0x0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0x14000170280)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_unix.go:614 +0x250
net.(*netFD).accept(0x14000170280)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/fd_unix.go:172 +0x28
net.(*TCPListener).accept(0x14000132678)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/tcpsock_posix.go:148 +0x28
net.(*TCPListener).Accept(0x14000132678)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/tcpsock.go:297 +0x2c
github.com/Shopify/sarama.(*MockBroker).serverLoop(0x14000170300)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:175 +0xdc
created by github.com/Shopify/sarama.NewMockBrokerListener
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:421 +0x42c

goroutine 38 [select]:
github.com/Shopify/sarama.handleResponsePromise({0x102dd7480, 0x1400010ff20}, {0x102dd74c8?, 0x1400010ff50}, 0x10a510328?, {0x102dd8ae0, 0x1400010fb60})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:1047 +0x88
github.com/Shopify/sarama.(*Broker).sendAndReceive(0x14000121c00, {0x102dd7480, 0x1400010ff20}, {0x102dd74c8?, 0x1400010ff50?})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:1043 +0x15c
github.com/Shopify/sarama.(*Broker).ApiVersions(0x10a4d1fe8?, 0x1030f0a68?)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:612 +0x50
github.com/Shopify/sarama.(*Broker).Open.func1.1()
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:188 +0xfc
github.com/Shopify/sarama.(*Broker).Open.func1()
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:275 +0x10c4
github.com/Shopify/sarama.withRecover(0x1400011cea0?)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:43 +0x40
created by github.com/Shopify/sarama.(*Broker).Open
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:180 +0x358

goroutine 3 [chan receive]:
github.com/Shopify/sarama.(*MockBroker).serverLoop.func1()
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:166 +0x2c
created by github.com/Shopify/sarama.(*MockBroker).serverLoop
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:165 +0x94

goroutine 40 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x102fc1960)
        /Users/gaggunchaggar/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475/meter.go:239 +0x30
created by github.com/rcrowley/go-metrics.NewMeter
        /Users/gaggunchaggar/go/pkg/mod/github.com/rcrowley/go-metrics@v0.0.0-20201227073835-cf1acfcdf475/meter.go:46 +0xd4

goroutine 41 [IO wait]:
internal/poll.runtime_pollWait(0x10a51e808, 0x72)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x14000170380?, 0x14000187000?, 0x0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x14000170380, {0x14000187000, 0x1000, 0x1000})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x14000170380, {0x14000187000?, 0x10a51e808?, 0x6fc23ab59?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x140001184f8, {0x14000187000?, 0x14000107da8?, 0x1029f0d18?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/net.go:183 +0x34
bufio.(*Reader).Read(0x1400011a540, {0x140001105c0, 0x8, 0x102c9e144?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/bufio/bufio.go:237 +0x1e0
github.com/Shopify/sarama.(*bufConn).Read(0x1400018f618?, {0x140001105c0?, 0x1400018f628?, 0x102c652f8?})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:107 +0x24
io.ReadAtLeast({0x10a521d28, 0x140001326c0}, {0x140001105c0, 0x8, 0x8}, 0x8)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/io/io.go:332 +0xa0
io.ReadFull(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/io/io.go:351
github.com/Shopify/sarama.(*Broker).readFull(0x14000121c00, {0x140001105c0, 0x8, 0x8})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:932 +0xc0
github.com/Shopify/sarama.(*Broker).responseReceiver(0x14000121c00)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:1131 +0xec
github.com/Shopify/sarama.withRecover(0x0?)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:43 +0x40
created by github.com/Shopify/sarama.(*Broker).Open.func1
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/broker.go:254 +0xca4

goroutine 4 [IO wait]:
internal/poll.runtime_pollWait(0x10a51e718, 0x72)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/runtime/netpoll.go:306 +0xa0
internal/poll.(*pollDesc).wait(0x1400006e080?, 0x140000141dc?, 0x0)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:84 +0x28
internal/poll.(*pollDesc).waitRead(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0x1400006e080, {0x140000141dc, 0x4, 0x4})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/internal/poll/fd_unix.go:167 +0x200
net.(*netFD).Read(0x1400006e080, {0x140000141dc?, 0x102ff98a0?, 0x1029f3c60?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/fd_posix.go:55 +0x28
net.(*conn).Read(0x1400000e010, {0x140000141dc?, 0x1400012bce8?, 0x1030f0108?})
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/net/net.go:183 +0x34
io.ReadAtLeast({0x102dd4960, 0x1400000e010}, {0x140000141dc, 0x4, 0x4}, 0x4)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/io/io.go:332 +0xa0
io.ReadFull(...)
        /opt/homebrew/Cellar/go/1.20.4/libexec/src/io/io.go:351
github.com/Shopify/sarama.(*MockBroker).readToBytes(0x1400007a000?, {0x102dd4960, 0x1400000e010})
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:194 +0x58
github.com/Shopify/sarama.(*MockBroker).handleRequests(0x14000170300, {0x10a704008?, 0x1400000e010}, 0x102a50fa4?, 0x14000170300?)
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:244 +0x27c
created by github.com/Shopify/sarama.(*MockBroker).serverLoop
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:177 +0xc8

goroutine 5 [select]:
github.com/Shopify/sarama.(*MockBroker).handleRequests.func2()
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:234 +0x60
created by github.com/Shopify/sarama.(*MockBroker).handleRequests
        /Users/gaggunchaggar/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/mockbroker.go:233 +0x254
FAIL    example 5.229s
FAIL
```

</p>
</details>

##### Problem Description

I am currently trying to write tests for a project when I have a particular implementation for a consumer group which I want to be able to test.

From what I have seen, I have to create a mock broker and then pass this to `NewClient`, then use `NewConsumerGroupFromClient` to create a consumer group with a mocked broker, then I can pass this group into my business logic and make my assertions.

However, I am having an issue where `NewClient` hangs indefinitely when creating from a mock broker. Could you please advice on what the issue is here?

Also could you please advise on the best way to send test data to my consumer group, is it to make a publisher from the same mock broker or is it to to use `MockFetchResponse`?

**Comment by dnwe** [comment]
I’d suggest setting up a sarama.Logger in your test so you can see what the mockbroker is doing. It’s likely it received a request that you don’t have a handler setup for and your client is just waiting indefinitely for a response
