### ISSUE TITLE
exception while closing the syncproducer

### ISSUE THREAD

**Issue by ajeyprasad** [IBM/sarama#2647]
##### Description

Created a kafka producer using NewSyncProducer method and will keep on sending messages. After sometime based on some conditions we are trying to stop the existing producer and will create the new producer. So when trying to stop the producer getting the below panic:
`panic: send on closed channel

goroutine 13651 [running]:
github.com/Shopify/sarama.(*asyncProducer).shutdown(0xc00044c000)
	/Users/a0p0j97/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/async_producer.go:1237 +0xa8
github.com/Shopify/sarama.withRecover(0xc001a85f00?)
	/Users/a0p0j97/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/utils.go:43 +0x3e
created by github.com/Shopify/sarama.(*asyncProducer).AsyncClose
	/Users/a0p0j97/go/pkg/mod/github.com/!shopify/sarama@v1.38.1/async_producer.go:385 +0x98
`

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|   v1.38.1 |  2.8  |  1.18   |

What might be wrong in this. Can you please help me out with this?

**Comment by dnwe** [comment]
@ajeyprasad I think the only way you could hit this panic would be if `producer.Close(...)` had been called more than once for the same producer, because it is only the Close path itself that will close the `input` channel, which is what your panic is saying is already closed when it tries to send the shutdown message to it

https://github.com/IBM/sarama/blob/6acb2767144a840d9cc423f2917617e3372da7be/async_producer.go#L1237-L1246
