### ISSUE TITLE
panic while processing malformed input in `decodeRequest`.

### ISSUE THREAD

**Issue by 0x34d** [IBM/sarama#2658]
##### Description

File : `sarama/request_test.go`

```go
func TestDecodeRequest(t *testing.T) {

	decodeRequest(bytes.NewReader([]byte("\x00\x00\x00\x0e\x002000000\x00\x000000")))
}
```

Run: `go test -run TestDecodeRequest`

Backtrace:
```log
--- FAIL: TestDecodeRequest (0.00s)
panic: runtime error: slice bounds out of range [:60] with capacity 14 [recovered]
	panic: runtime error: slice bounds out of range [:60] with capacity 14

goroutine 6 [running]:
testing.tRunner.func1.2({0x9bcc60, 0xc00002c570})
	/usr/lib/golang/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
	/usr/lib/golang/src/testing/testing.go:1529 +0x39f
panic({0x9bcc60, 0xc00002c570})
	/usr/lib/golang/src/runtime/panic.go:884 +0x213
github.com/IBM/sarama.(*realDecoder).getCompactString(0xc0000a45a0)
	/home/0x34d/project/sarama/real_decoder.go:261 +0x10e
github.com/IBM/sarama.(*DescribeUserScramCredentialsRequest).decode(0xc00007e540, {0xad6570, 0xc0000a45a0}, 0x45a0?)
	/home/0x34d/project/sarama/describe_user_scram_credentials_request.go:42 +0x12b
github.com/IBM/sarama.(*request).decode(0xc0000afe00, {0xad6570, 0xc0000a45a0})
	/home/0x34d/project/sarama/request.go:85 +0x154
github.com/IBM/sarama.decode({0xc000028b30, 0xe, 0xe}, {0xacbaa0, 0xc0000afe00}, {0x0, 0x0})
	/home/0x34d/project/sarama/encoder_decoder.go:69 +0x162
github.com/IBM/sarama.decodeRequest({0xaca840, 0xc0000afdd0})
	/home/0x34d/project/sarama/request.go:113 +0x16c
github.com/IBM/sarama.TestDecodeRequest(0x0?)
	/home/0x34d/project/sarama/request_test.go:466 +0xae
testing.tRunner(0xc0000d6b60, 0xa37468)
	/usr/lib/golang/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1629 +0x3ea
exit status 2
FAIL	github.com/IBM/sarama	0.006s
```

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
| commit e16473b64119822c6b78b8063b3332d7908bee74   |   ???  | go version go1.20.8 linux/amd64 |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```

```

</p>
</details>

**Comment by Mateusnasciment** [comment]
"slicebounds out of range" occurs in relation to the Sarama project code during the TestDecodeRequest test. You need to check slice boundaries across multiple files and ensure compatibility with dependencies in the Go 1.20.8 environment. If the problem persists, check again
