### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by kansnow** [IBM/sarama#2977]
##### Description

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0c9f5]

goroutine 1026 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc0031423c0, 0x1)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:620 +0x2f5
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc0031423c0)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:564 +0x68d
github.com/Shopify/sarama.withRecover(0xc002cf6f80)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/utils.go:43 +0x3f
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:515 +0x2e5
```

##### Versions

| Sarama | Kafka | Go  |
| ------ | ----- | --- |
|     1.36.0   | 2.6.0      | 1.20.5    |

##### Configuration

```go

```

##### Logs

<details><summary>logs: CLICK ME</summary>
<p>

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa0c9f5]

goroutine 1026 [running]:
github.com/Shopify/sarama.(*partitionProducer).newHighWatermark(0xc0031423c0, 0x1)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:620 +0x2f5
github.com/Shopify/sarama.(*partitionProducer).dispatch(0xc0031423c0)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:564 +0x68d
github.com/Shopify/sarama.withRecover(0xc002cf6f80)
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/utils.go:43 +0x3f
created by github.com/Shopify/sarama.(*asyncProducer).newPartitionProducer
        C:/Users/sangfor/go/pkg/mod/github.com/!shopify/sarama@v1.36.0/async_producer.go:515 +0x2e5

```

</p>
</details>
Using asynchronous methods to send data to Kafka, suddenly blocking the IP address that was produced to Kafka and continuously consuming data to push to the input. After a period of time, an error occurs

**Comment by puellanivis** [comment]
This was addressed in a previous PR: https://github.com/IBM/sarama/pull/2387

Please update to at least `v1.43.3`

**Comment by dnwe** [comment]
Yep, note that the module import path has also changed to github.com/IBM/sarama since ownership transitioned away from Shopify in v1.40.0 onwards

**Comment by kansnow** [comment]
> This was addressed in a previous PR: #2387
> 
> Please update to at least `v1.43.3`

okay, think you very much

**Comment by kansnow** [comment]
> Yep, note that the module import path has also changed to [github.com/IBM/sarama](https://github.com/IBM/sarama) since ownership transitioned away from Shopify in v1.40.0 onwards

Okay, received

**Comment by kansnow** [comment]
The problem has been resolved
